binaryTree/src/main/kotlin/org/tree/binaryTree/BinSearchTree.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/Nodes.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/TemplateBSTree.kt
Добавлен абстрактный класс `TemplateBSTree`, для него реализованны следующие основные методы:
- `insert()`
- `find()`
- `remove()`
Прошу обратить особое внимание на [код связанный с последним методом](https://github.com/spbu-coding-2022/trees-2/commit/1f148427a70a1bce11d71af3eb931f9e870cecd1), так как я в нем сильно сомневаюсь. 
От `TemplateBSTree` отнаследован класс `BinSearchTree`, который добавляет только реализацию метода `insert()`.
---
Так же в ходе написания `TemplateBSTree`, класс `TemplateNode` получил два вспомогательных метода:
- `getNonNullChild()` - возвращает любого ненулевого ребенка
- `countNullChild()` - возвращает кол-во нулевых детей
=> Добавленна реализация абстрактного класса TemplateBSTree и класса BinSearchTree

binaryTree/src/main/kotlin/org/tree/binaryTree/TemplateBalanceBSTree.kt
Для абстрактного класса `TemplateBalanceBSTree` добавлены методы `rotateRight()` и `rotateLeft()`.
=> Добавлены повороты

binaryTree/src/main/kotlin/org/tree/binaryTree/Nodes.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/TemplateBSTree.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/TemplateBalanceBSTree.kt
=> Небольшой рефакторинг кода

binaryTree/src/main/kotlin/org/tree/binaryTree/Nodes.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/TemplateBSTree.kt
Добавлены обходы для дерева и вершин. Может быть полезно при написании тестов.
=> Добавлены методы обхода

binaryTree/src/main/kotlin/org/tree/binaryTree/TemplateBalanceBSTree.kt
Для метода `balance()` добавлена возможность балансировки корневой ноды.
=> Добавлен случай балансировки root'а

.github/workflows/actions.yml, buildSrc/src/main/kotlin/org.tree.kotlin-common-conventions.gradle.kts
Теперь к отчетам о прохождении тестов, добавлены отчеты о том насколько тесты покрывают код.
=> Добавлено отслеживание покрытия тестами

binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/TemplateBSTree.kt
Реализована частичная функциональность красно-черного дерева. Рассмотрен случай вставки. 
Остался случай балансировки удаления узла.
=> Добавление класса RB Tree

binaryTree/src/main/kotlin/org/tree/binaryTree/TemplateBSTree.kt
Теперь публичные методы `insert()` и `remove()` класса `TemplateBSTree` возвращают изменили ли они дерево или нет.
=> Добавлено возращаемое значение для методов insert() и remove()

buildSrc/src/main/kotlin/org.tree.kotlin-common-conventions.gradle.kts
К проекту добавлена библиотека hamcrest, что чуть упрощает написание тестов. Хотелось бы чтобы для написания тестов пользовались её возможностями. 
Почитать о hamcrest можно тут - https://sysout.ru/rabota-s-hamcrest/
=> Подключен Hamcrest

binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
Был кейс когда дерево не балансировалось при вставке элемента как должно было, теперь оно балансируется.
=> Исправлена ошибка при вставке в RB дереве

binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
Теперь дерево проходит локальные тесты на удаление элементов. Смерджите этот pr прежде чем смерджить https://github.com/spbu-coding-2022/trees-2/pull/26
=> Исправлены ошибки при удалении в RB дереве

binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
Добавлено сбалансированное удаление в RB Tree
RB Tree готов! (Если без багов...)
=> Добавлено сбалансированное удаление в RB Tree

binaryTree/src/test/kotlin/org/tree/binaryTree/BinSearchTreeTest.kt, binaryTree/src/test/kotlin/org/tree/binaryTree/Util.kt
Добавлены тесты для `BinSearchTree`, которые проверяют следующие публичные методы абстрактного класса `TemplateBSTree`:
-   `insert()`
-   `remove()`
-   `find()`
-   `traversal()`
---
Так же добавлена функция для быстрого создания дерева из списка вершин и функции для проверки корректности бинарного дерева поиска.
=> Добавлены тесты для BinSearchTree

binaryTree/src/test/kotlin/org/tree/binaryTree/BinSearchTreeTest.kt, binaryTree/src/test/kotlin/org/tree/binaryTree/RBTreeTest.kt, binaryTree/src/test/kotlin/org/tree/binaryTree/Util.kt
Добавлены тесты проверяющие коректность работы (правильную балансировку) методов `insert` и `remove`
=> Добавлены тесты для RBTree

binaryTree/src/main/kotlin/org/tree/binaryTree/KeyValuePair.kt
Добавлен класс `KVP` (KeyValuePair), для того чтобы в дереве можно было хранить пару ключ значение.
=> Добавлен класс пара-ключ-значение

binaryTree/src/test/kotlin/org/tree/binaryTree/NodeTest.kt
Добавлены тесты для класса `Node`, для того чтобы проверить коректную работу публичных методов абстрактного класса `TemplateNode`
=> Добавлены тесты для вершин

binaryTree/src/main/kotlin/org/tree/binaryTree/templates/TemplateBalanceBSTree.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/trees/AVLTree.kt, binaryTree/src/test/kotlin/org/tree/binaryTree/AVLTreeTest.kt, binaryTree/src/test/kotlin/org/tree/binaryTree/Util.kt
Добавлены тесты, проверяющие корректность работы методов `insert` и `remove`. Исправлены выявленные тестами проблемы балансировки дерева.
=> Добавлены тесты для AVLTree

.github/workflows/actions.yml
Теперь проект собирается и тесты прогоняются на нескольких операционных системах.
=> CI: добавлен билд на нескольких ос

app/build.gradle.kts, app/src/main/kotlin/org/tree/app/controller/io/Neo4jIO.kt, app/src/main/kotlin/org/tree/app/view/NodeView.kt
Теперь красно черное дерево можно сохранять в базу neo4j. Указав url адрес базы и логин/пароль, можно либо сохранить дерево, либо загрузить его оттуда. Код пока только примерный и может поменяться при кокретной реализации.
---
Лучше смотреть сразу финальную версию кода (не отдельно по коммитам), так как он несколько раз переписывался.
=> Добавленно сохранение красночерного дерева

app/src/main/kotlin/org/tree/app/controller/io/Neo4jIO.kt
Чуть переработана архитектура хранения деревьев в neo4j. Новая архитектура позвоялет хранить несколько деревьев в одной базе, различая их по именам.
=> Добавлено хранение нескольких деревьев в neo4j

app/build.gradle.kts, app/src/main/kotlin/org/tree/app/controller/io/SQLiteIO.kt
=> Добавление класса SQLiteIO c поддержкой SQLite

app/build.gradle.kts, app/src/main/kotlin/org/tree/app/controller/io/SQLiteIO.kt
=> Hotfix: add sqlite

binaryTree/src/main/kotlin/org/tree/binaryTree/templates/TemplateBSTree.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/templates/TemplateBalanceBSTree.kt
Исправлена проблема упомянутая в  https://github.com/spbu-coding-2022/trees-2/issues/49
=> Устранена проблема равенства

README.md, binaryTree/src/main/kotlin/org/tree/binaryTree/KeyValuePair.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/templates/TemplateBSTree.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/templates/TemplateNode.kt, binaryTree/src/test/kotlin/org/tree/binaryTree/NodeTest.kt, binaryTree/src/test/kotlin/org/tree/binaryTree/RBTreeTest.kt
Небольшой рефакторинг проекта после получения обратной связи.
=> Рефакторинг проекта

app/src/main/kotlin/org/tree/app/controller/io/Neo4jIO.kt
Добавил в код константы: название меток и связей. 
Также переписал запросы с использованием параметров, что должно сделать код безопаснее и труднее ломающимся (раньше все падало если в значении ноды хранить строчку с `"`). 
И еще разделил один большой запрос на несколько маленьких с параметрами по совету Вовы, теперь мы можем сохранять и загружать деревья на 100000 элементов секунд за 5.
=> Улучшена работа с neo4j

README.md, app/build.gradle.kts, app/src/main/kotlin/org/tree/app/controller/io/Json.kt
Изменен способ хранения нод: храним не ключи от правого и левого ребенка, а самих детей и их детей и т.д. Теперь на вход всем методам передается файл.
=> Переписан класс Json

binaryTree/src/main/kotlin/org/tree/binaryTree/trees/RBTree.kt
Повышение читаемости кода за счет рефакторинга (по подсказкам c ревью):
- Добавлены комментарии
- `return 0` заменен на `return` в виду ненадобности возвращаемого значения
- Добавлена ссылка на источник алгоритма
=> Рефакторинг красно-черного дерева

app/src/main/kotlin/org/tree/app/controller/io/SQLiteIO.kt, binaryTree/src/main/kotlin/org/tree/binaryTree/KeyValuePair.kt
- Для обработки стал использоваться API DAO
- Добавлен вспомогательный метод `addCoordinatesForNodeView` для обновления координат у `nodeView` (повышение читаемости кода)
- Исправлен и оптимизирован `importTree`
- Переписан метод `exportTree` (теперь использует DAO) 
- `KVP` стал `data class` в виду того, что так удобнее проводить тесты (которых нет)
------
Но все это ерунда, потому что в соседнем PR @osogi меняет архитектуру...
=> Исправление ошибок и оптимизация SQLite

README.md, app/src/main/kotlin/org/tree/app/controller/io/SQLiteIO.kt
- Переписан класс `SQLiteIO` 
- Добавлена информация о работе SQLite в `README`
=> Доработка SQLite 

app/src/main/kotlin/org/tree/app/controller/TreeController.kt
Теперь координаты каждой ноды зависят от ее высоты и количества ее детей, благодаря чему получаем более красивую отрисовку дерева.
__________________________________________________________________________________________________________________________________________
Возможно стоит улучшить(исправить?), только пока не знаю как
=> Изменен способ получения координат вершин

app/src/main/kotlin/org/tree/app/App.kt, app/src/main/kotlin/org/tree/app/controller/TreeController.kt, app/src/main/kotlin/org/tree/app/view/AutoSizedText.kt, app/src/main/kotlin/org/tree/app/view/ImportRemoveFindRows.kt, app/src/main/kotlin/org/tree/app/view/Line.kt, app/src/main/kotlin/org/tree/app/view/Logger.kt, app/src/main/kotlin/org/tree/app/view/Node.kt, app/src/main/kotlin/org/tree/app/view/Tree.kt, app/src/main/kotlin/org/tree/app/view/dialogs/io/Neo4jConnect.kt
- теперь все более красивое
- изменяемый размер текста для нод
- лог
=> Приведена в порядок основная часть GUI 

app/src/main/kotlin/org/tree/app/App.kt, app/src/main/kotlin/org/tree/app/controller/io/AppDataController.kt, app/src/main/kotlin/org/tree/app/controller/io/SQLiteIO.kt, app/src/main/kotlin/org/tree/app/view/dialogs/io/FilesIOHandler.kt, app/src/main/kotlin/org/tree/app/view/dialogs/io/Neo4jConnect.kt, app/src/main/kotlin/org/tree/app/view/dialogs/io/Neo4jDialogs.kt
Теперь приложени сохраняет свои данные, такие как:
- данные для работы с neo4j
- последнее дерево с которым работал пользователь
Так же при запуске приложения пытается открыться последннее дерево.
=> Добавлено сохранение данных приложения

README.md, app/src/main/kotlin/org/tree/app/App.kt, app/src/main/kotlin/org/tree/app/controller/TreeController.kt, app/src/main/kotlin/org/tree/app/controller/io/AppDataController.kt, app/src/main/kotlin/org/tree/app/controller/io/SQLiteIO.kt, app/src/main/kotlin/org/tree/app/view/Tree.kt, app/src/main/kotlin/org/tree/app/view/dialogs/io/FilesIOHandler.kt, app/src/main/kotlin/org/tree/app/view/dialogs/io/Neo4jConnect.kt, app/src/main/kotlin/org/tree/app/view/dialogs/io/Neo4jDialogs.kt
- Добавлена поддержка `json` файлов
- Добавлена поддержка `sqlite` файлов
- Слегка изменена структура кода приложения
- Изменились некоторые названия переменных
=> Добавлена возможность выбора файлов для импортирования/экспортирования деревьев из баз данных

app/src/main/kotlin/org/tree/app/controller/TreeController.kt
Теперь мы считаем широты(widths) и, опираясь на них, высчитываем координаты. Также теперь корень не бегает по окошку, а всегда остается в точке (0, 0).
=> Новый способ получения координат вершин

binaryTree/src/main/kotlin/org/tree/binaryTree/trees/AVLTree.kt, binaryTree/src/test/kotlin/org/tree/binaryTree/AVLTreeTest.kt
**AVLTree**
- Переименованы методы: `fixheight` -> `fixHeight`, `bfactor` -> `balanceFactor`, `height` -> `heightOrZero`
- К методу `balanceFactor` добавлен поясняющий комментарий
- Переписан код балансировки.
**AVLTreeTest**
- Убраны лишние пустые строчки
- Оператор `and` заменен на `&&`.
=> Рефакторинг АВЛ

app/src/main/kotlin/org/tree/app/App.kt, app/src/main/kotlin/org/tree/app/controller/io/HandledIOException.kt, app/src/main/kotlin/org/tree/app/controller/io/Neo4jIO.kt, app/src/main/kotlin/org/tree/app/view/dialogs/AlertDialog.kt, app/src/main/kotlin/org/tree/app/view/dialogs/ExitDialog.kt, app/src/main/kotlin/org/tree/app/view/dialogs/io/Neo4jConnect.kt, app/src/main/kotlin/org/tree/app/view/dialogs/io/Neo4jDialogs.kt
Теперь при выходе из приложения у пользователя уточняется хочет ли он выйти + дает возможность сразу сохранить дерево (к сожалению пока не закрывается после сохранения)
=> Добавлен диалог выхода

app/src/main/kotlin/org/tree/app/controller/io/SQLiteIO.kt
- Удалено свойство класса для отображения количества элементов множества
- Обработка данных после копирования теперь вынесены за транзакцию в Kotlin Exposed
- Изменен порядок определения функций: теперь они расположены более интуитивно понятно
=> Улучшение кода SQLite по мотивам ревью

app/src/main/kotlin/org/tree/app/App.kt, app/src/main/kotlin/org/tree/app/controller/TreeController.kt, app/src/main/kotlin/org/tree/app/view/Node.kt, app/src/main/kotlin/org/tree/app/view/Tree.kt
- теперь линия не убегает за экран
- выкинут устаревший код
=> Поправил проблему в гуи

README.md, binaryTree/src/main/kotlin/org/tree/binaryTree/trees/RBTree.kt
- Небольшая оптимизация метода `getBlackHeight`
- Поправлены разделители строк
- Упрощен код c проверкой на `null`
- Удалены лишние `return`'ы
=> Рефакторинг RBTree
